version: "3.5"
services:
        v2ray:
            image: v2fly/v2fly-core
            ports: 
                - 6666:6666
            volumes: 
                - "${PWD}:/etc/v2ray"
                